In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('bank-additional-full_normalised.csv')

In [3]:
df

,age,job=housemaid,job=services,job=admin.,job=blue-collar,job=technician,job=retired,job=management,job=unemployed,job=self-employed,...,previous,poutcome=nonexistent,poutcome=failure,poutcome=success,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,class
0,0.209877,0,0,0,0,0,0,0,0,0,...,0.000000,1,0,0,1.000000,0.882307,0.376569,0.980730,1.000000,0
1,0.296296,0,0,1,0,0,0,0,0,0,...,0.000000,1,0,0,1.000000,0.484412,0.615063,0.981183,1.000000,0
2,0.246914,1,0,0,0,0,0,0,0,0,...,0.000000,1,0,0,0.937500,0.698753,0.602510,0.957379,0.859735,0
3,0.160494,0,1,0,0,0,0,0,0,0,...,0.142857,0,1,0,0.333333,0.269680,0.192469,0.150759,0.512287,0
4,0.530864,0,0,0,1,0,0,0,0,0,...,0.000000,1,0,0,0.333333,0.340608,0.154812,0.174790,0.512287,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,0.271605,0,0,0,1,0,0,0,0,0,...,0.000000,1,0,0,0.333333,0.269680,0.192469,0.158694,0.512287,0
41184,0.333333,0,0,0,0,0,0,1,0,0,...,0.000000,1,0,0,0.687500,0.389322,0.368201,0.767853,0.877883,1
41185,0.172840,0,0,0,0,1,0,0,0,0,...,0.000000,1,0,0,0.937500,0.698753,0.602510,0.956926,0.859735,0
41186,0.148148,0,0,1,0,0,0,0,0,0,...,0.000000,1,0,0,1.000000,0.882307,0.376569,0.980503,1.000000,0
41187,0.382716,0,0,0,0,1,0,0,0,0,...,0.000000,1,0,0,0.937500,0.698753,0.602510,0.957379,0.859735,0

In [12]:
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Assuming df is your DataFrame with transaction data
# Preprocess data (example for scaling)
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df.drop(['class'], axis=1))

# Train Isolation Forest
clf = IsolationForest(n_estimators=100, contamination='auto')
clf.fit(scaled_features)

# Predict anomalies
df['anomaly'] = clf.predict(scaled_features)

In [17]:
df['anomaly'] = df['anomaly'].map({-1: 1, 1: 0})

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(df['class'], df['anomaly']))
print(confusion_matrix(df['class'], df['anomaly']))

              precision    recall  f1-score   support

           0       0.91      0.96      0.93     36548
           1       0.42      0.24      0.31      4640

    accuracy                           0.88     41188
   macro avg       0.67      0.60      0.62     41188
weighted avg       0.85      0.88      0.86     41188

[[35005  1543]
 [ 3506  1134]]

In [21]:
# Get anomaly scores
df['scores'] = clf.decision_function(scaled_features)

# Examine the highest scoring anomalies
anomalies = df.sort_values(by='scores').head(20)

In [22]:
anomalies

,age,job=housemaid,job=services,job=admin.,job=blue-collar,job=technician,job=retired,job=management,job=unemployed,job=self-employed,...,poutcome=failure,poutcome=success,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,class,anomaly,scores
31435,0.160494,0,0,0,0,0,0,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.055543,0.000000,0,1,-0.120132
5322,0.604938,0,0,0,0,0,1,0,0,0,...,0,1,0.479167,0.935308,0.054393,0.079574,0.000000,1,1,-0.115553
36496,0.851852,0,0,0,0,0,1,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.055090,0.000000,1,1,-0.114504
10991,0.827160,0,0,0,0,0,1,0,0,0,...,0,1,0.479167,0.935308,0.054393,0.082974,0.000000,0,1,-0.107327
13240,0.185185,0,0,1,0,0,0,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.056223,0.000000,1,1,-0.103277
13074,0.296296,0,0,0,0,1,0,0,0,0,...,0,1,0.104167,0.296960,0.418410,0.142371,0.425709,1,1,-0.103004
1319,0.148148,0,0,0,0,0,0,0,0,0,...,0,1,0.104167,0.000000,0.811715,0.056676,0.425709,1,1,-0.102923
12483,0.827160,0,0,0,0,0,1,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.055090,0.000000,1,1,-0.099143
11088,0.580247,0,0,0,0,0,1,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.055316,0.000000,1,1,-0.096588
9455,0.481481,0,0,0,0,0,0,0,1,0,...,0,1,0.479167,0.935308,0.054393,0.076627,0.000000,1,1,-0.096159
3654,0.827160,0,0,0,0,0,1,0,0,0,...,0,1,0.354167,0.784879,0.439331,0.058717,0.105860,1,1,-0.095975
33912,0.530864,0,0,0,0,0,1,0,0,0,...,1,0,0.479167,0.935308,0.054393,0.076627,0.000000,0,1,-0.095217
37963,0.148148,0,0,1,0,0,0,0,0,0,...,0,1,0.354167,0.722525,0.460251,0.020177,0.105860,0,1,-0.095177
37765,0.209877,0,0,0,0,1,0,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.056450,0.000000,0,1,-0.094207
3296,0.172840,0,0,0,0,0,0,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.055770,0.000000,1,1,-0.091257
29489,0.000000,0,0,0,0,0,0,0,0,0,...,0,1,0.000000,0.089634,1.000000,0.024484,0.203781,1,1,-0.090947
38745,0.160494,0,0,0,0,1,0,0,0,0,...,1,0,0.479167,0.778644,0.556485,0.055090,0.000000,1,1,-0.088327
21878,0.074074,0,0,0,0,1,0,0,0,0,...,0,1,0.354167,0.722525,0.460251,0.015416,0.105860,0,1,-0.086865
21630,0.641975,0,0,0,0,0,1,0,0,0,...,0,1,0.479167,0.778644,0.556485,0.057130,0.000000,1,1,-0.086801
31597,0.790123,0,0,0,0,0,1,0,0,0,...,0,1,0.000000,0.089634,1.000000,0.021310,0.203781,0,1,-0.086372